[package]
name = "rust-ray-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.9"
minifb = "0.28.0"
threadpool = "1.8.1"
